In [ ]:
Python 
---------
ML Libs - numpy pandas matplotlib scipy skitlean torch ...
-------
anaconda install - ML + DA Libs + GIL disabled 
----------------- ====================

download python from python.org => cpython - we can do python program ...
                                             pip install numpy
                                             pip install pandas 
                                             ...
                                             Multithreading - GIL enabled 

ipython
jython
..

In [ ]:
python - class <--> object //design style
           |        |_ real entity 
          Type
int float str bool bytes NoneType list tuple dict set //native types 

    10 - class int
    10.0 - class float
    '10.0' - class str

In [1]:
a = 10
b = 3+7
c = 4+6
d = 2+8
print(hex(id(a)),hex(id(b)),hex(id(c)),hex(id(d)),hex(id(10)))

0x7ffe24845ad8 0x7ffe24845ad8 0x7ffe24845ad8 0x7ffe24845ad8 0x7ffe24845ad8


In [ ]:
Python programming
- procedure style - direct approach style
                    ------------------------
                        var = 10
                        def fx():
                             ....
                        fx() <== direct function call
                        print(var) 


- object oriented style 
                        class className:
                             ...
                             def fx(self):
                                  .....
                        obj1 = className()
                        obj1.var = 10  # object based initialization
                        obj2.var = 10
                        obj1.fx() # method call 

- Functional style  - Single line Code - this is not block style Code
                    list(map(lambda <operation>,collection))

In [3]:
L = []

def f1(a):
    return a + 100

for var in range(1,10):
    r = f1(var)
    L.append(r)

L

[101, 102, 103, 104, 105, 106, 107, 108, 109]

In [5]:
list(map(lambda a:a+100,range(1,10)))

[101, 102, 103, 104, 105, 106, 107, 108, 109]

In [7]:
d={}
d['K1']=list(map(lambda a:a+100,range(1,10)))
d['K2']={'Kx':list(map(lambda a:a+100,range(1,10)))}
d

{'K1': [101, 102, 103, 104, 105, 106, 107, 108, 109],
 'K2': {'Kx': [101, 102, 103, 104, 105, 106, 107, 108, 109]}}

In [ ]:
Python native types
int float complex - numberbased 
          -------
True False - bool 
None - NoneType

Arithmetic - inputTypes (int,float) ->int,float
String - inputType(int,str) -> str
Relational - inputTypes( int,float,str) ->bool
Logical  - inputTypes(int,float,str) ->bool
Membership - inputTypes(str,bytes,list,tuple,dict,set) ->bool
 (in non in) 
identity  - class,object  ->bool
is isnot  

In [19]:
a = 10
type(a) is int

True

In [21]:
type(10) is int

True

In [23]:
type(10.0) is int

False

In [ ]:
conditional statement - Code validation 
if statement 
Looping statement 
collection style - str bytes list tuples dict set - for keyword 
condition style  - based on bool ->True ->ok       - while keyword
                                 ->False ->block won't execute

Object oriented programming
class 
object
method
   |->special methods 
   |->decorator 
inheritance 

Functional programming
------------------------
lambda 
comprehension
generator 
map,filter,enumerate 
-----------------------------------------------------------
networkx
numpy ->pandas ->matplotlib -> pytorch ... 
nlp ->nlptk - embedding ...
------------------------------------------------------------

In [ ]:
class - type
      - attributes
      - mutable type - we can add new attribute; modifiy; delete 
Syntax:-
---------
class className:
    <attribute>
className.<attribute>    => AttributeError 
className.<existingAttribute>=updateValue
del(className.<attribute>)

     +-------------------------------+
     |  [ ]   []         |   |       |   <== blueprint sheet  - class 
     |              (white)          |
     +-------------------------------+

className() # constructor - object creation
+-----------------+    +--------------+
|[] []      |   | |    |[][]     |   ||
|   (white)       |    | (white)      |
+-----------------+    +--------------+
   Building-B1            Building-B2  - object
    1st main                2nd main 
    0x1234                  0x3231

In [25]:
class enrollment:
    name = ''
    dob = ''
    place = ''

In [27]:
print(type(enrollment))

<class 'type'>


In [31]:
print(type(int),type(float),type(list),type(bool),type(enrollment))

<class 'type'> <class 'type'> <class 'type'> <class 'type'> <class 'type'>


In [33]:
obj1 = enrollment()
obj1.name = 'arun'
obj1.dob = '1st Jan'
obj1.place = 'City-1'

obj2 = enrollment()
obj2.name = 'anu'
obj2.dob = '2nd Feb'
obj2.place = 'City-2'

In [35]:
print(f'Emp name is:{obj1.name}, DOB:{obj1.dob}, City:{obj1.place}')
print('')
print(f'Emp name is:{obj2.name}, DOB:{obj2.dob}, City:{obj2.place}')

Emp name is:arun, DOB:1st Jan, City:City-1

Emp name is:anu, DOB:2nd Feb, City:City-2


In [37]:
obj2.place='City-3' # we can update to specific attribute

In [39]:
print(f'Emp name is:{obj1.name}, DOB:{obj1.dob}, City:{obj1.place}')
print('')
print(f'Emp name is:{obj2.name}, DOB:{obj2.dob}, City:{obj2.place}')

Emp name is:arun, DOB:1st Jan, City:City-1

Emp name is:anu, DOB:2nd Feb, City:City-3


In [43]:
class product:
    pname = 'prodX'

print(product.pname)
product.pname = 'pX' # overwrite 
print(product.pname)

prodX
pX


In [45]:
obj1 = product()
obj1.pname

'pX'

In [47]:
obj1.pname = 'B1' # object based - initialization
print(obj1.pname)

B1


In [49]:
obj2 = product()
obj2.pname

'pX'

In [55]:
def f1():
    print("Hello")

# f1() # Hello
# f1(10) TypeError: f1() takes 0 positional arguments but 1 was given

In [59]:
class product:
    pid = 101
    def f2():
        print('display product details')

# pid  - class attribute
# f2   - class attribute
obj = product()
print(obj.pid)
# obj.f2() //methodCall -> f2(obj)

101


TypeError: product.f2() takes 0 positional arguments but 1 was given

In [63]:
class product:
    def f2(self):
        print("self=",self)

obj1=product()
print("obj1=",obj1)
obj1.f2() # f2(obj1)
print('')
obj2 = product()
print("obj2=",obj2)
obj2.f2() # f2(obj2)

obj1= <__main__.product object at 0x00000257B4781F10>
self= <__main__.product object at 0x00000257B4781F10>

obj2= <__main__.product object at 0x00000257B47830B0>
self= <__main__.product object at 0x00000257B47830B0>


In [ ]:
#obj2.f2("D1","D2") => f2(obj2,"D1","D2") -> def f2(self,a1,a2):

In [65]:
class enrollment:
    name = ''
    dob = ''
    place = ''
    def f1(self,n,d,p):
        '''initialization'''
        self.name = n
        self.dob = d
        self.place = p
        print('Enrollment is done')
    def f2(self):
        '''display emp details'''
        print(f'Emp name:{self.name} DOB:{self.dob} Place:{self.place}')
    def f3(self,p):
        '''update emp working city'''
        self.place = p
        print(f'{self.name} updated city details is:')
        self.f2() # nested method Call

In [67]:
obj1 = enrollment()
obj1.f1('arun','1st jan','City1')

Enrollment is done


In [69]:
obj2 = enrollment()
obj2.f1('Anu','2nd Feb','City2')

Enrollment is done


In [71]:
obj1.f2()

Emp name:arun DOB:1st jan Place:City1


In [73]:
obj2.f2()

Emp name:Anu DOB:2nd Feb Place:City2


In [75]:
obj2.f3('Pune')

Anu updated city details is:
Emp name:Anu DOB:2nd Feb Place:Pune


In [77]:
obj2.f2()

Emp name:Anu DOB:2nd Feb Place:Pune


In [79]:
obj3 = enrollment()
obj3.f2()

Emp name: DOB: Place:


In [81]:
obj3.f1('vijay','3rd March','City-3')

Enrollment is done


In [83]:
obj3.f2()

Emp name:vijay DOB:3rd March Place:City-3


#DataBase - establish db connection ->do query1 query2 ...queryN

class DBI:
    def connect(self,....):
        ....
    def method1(self):
        '''Query1'''
    def method2(self):
        '''Query2'''

obj = DBI()
obj.method2() # in OOPs - OK;  DB-Appln -DB Error 
In python any variable name <or> method name starts with __<label>__ <== pre-defined attribute
__init__()

>>> class product:
...     def f1(self):
...         print("product details")
...
>>> product()
<__main__.product object at 0x000001B9F7A441A0>
>>> obj = product()
>>> obj.f1()
product details
>>>
>>> class product:
...     def __init__(self):
...         print("product details")
...
>>> product()
product details
<__main__.product object at 0x000001B9F7A446E0>
>>>
>>> obj=product()
product details
>>

>>> class myclass:
...     def __init__(self):
...         print("initialization")
...     def __del__(self):
...         print("Thank you")
...
>>> obj = myclass()
initialization
>>> del(obj)
Thank you
>>>
>>> obj = myclass()
initialization
>>> exit


()
Thank you


In [85]:
class enrollment:
    def __init__(self,n,d,p):
        '''initialization'''
        self.name = n
        self.dob = d
        self.place = p
        print('Enrollment is done')
    def f2(self):
        '''display emp details'''
        print(f'Emp name:{self.name} DOB:{self.dob} Place:{self.place}')
    def f3(self,p):
        '''update emp working city'''
        self.place = p
        print(f'{self.name} updated city details is:')
        self.f2() # nested method Call

In [87]:
obj1 = enrollment('Arun','1st Jan','City-1')
obj2 = enrollment('Anu','2nd Feb','City-2')

Enrollment is done
Enrollment is done


In [89]:
obj1.f2()

Emp name:Arun DOB:1st Jan Place:City-1


In [91]:
obj2.f2()

Emp name:Anu DOB:2nd Feb Place:City-2


In [93]:
objX = enrollment()

TypeError: enrollment.__init__() missing 3 required positional arguments: 'n', 'd', and 'p'

In [95]:
objX

NameError: name 'objX' is not defined

In [99]:
# help(int)        
dir(int)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'is_integer',
 

In [101]:
dir(enrollment)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'f2',
 'f3']

In [103]:
class myclass:
    def __init__(self,a=0):
        self.a = a
    def __str__(self):
        return str(self.a+100)
    def __len__(self):
        return 10
    def __del__(self):
        del(self.a)

In [105]:
obj = myclass(15)

In [107]:
str(obj)

'115'

In [109]:
len(obj)

10

In [111]:
del(obj)

In [113]:
import pandas
print(pandas.DataFrame)

<class 'pandas.core.frame.DataFrame'>


In [ ]:
pandas/
   |___core/
        |____frame.py
                |_________class DataFrame:
                                   ....

In [117]:
# To get list of all the class attributes
dir(pandas.DataFrame)
print(len(dir(pandas.DataFrame)))

437


In [119]:
class product:
    '''about product details'''

In [121]:
product.__doc__

'about product details'

In [123]:
print(pandas.DataFrame.__doc__)


    Two-dimensional, size-mutable, potentially heterogeneous tabular data.

    Data structure also contains labeled axes (rows and columns).
    Arithmetic operations align on both row and column labels. Can be
    thought of as a dict-like container for Series objects. The primary
    pandas data structure.

    Parameters
    ----------
    data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
        Dict can contain Series, arrays, constants, dataclass or list-like objects. If
        data is a dict, column order follows insertion-order. If a dict contains Series
        which have an index defined, it is aligned by its index. This alignment also
        occurs if data is a Series or a DataFrame itself. Alignment is done on
        Series/DataFrame inputs.

        If data is a list of dicts, column order follows insertion-order.

    index : Index or array-like
        Index to use for resulting frame. Will default to RangeIndex if
        no indexing informat

In [129]:
class product:
    '''about product px class details'''
    pid = 101
    pname = 'pX'
    def f1(self):
        pass
    def f2(self):
        pass
    results = ['D1','D2']

In [131]:
product.__dict__ 

mappingproxy({'__module__': '__main__',
              '__doc__': 'about product px class details',
              'pid': 101,
              'pname': 'pX',
              'f1': <function __main__.product.f1(self)>,
              'f2': <function __main__.product.f2(self)>,
              'results': ['D1', 'D2'],
              '__dict__': <attribute '__dict__' of 'product' objects>,
              '__weakref__': <attribute '__weakref__' of 'product' objects>})

In [133]:
print(pandas.DataFrame.__dict__)

{'__module__': 'pandas.core.frame', '__annotations__': {'_accessors': 'set[str]', '_hidden_attrs': 'frozenset[str]', '_mgr': 'BlockManager | ArrayManager', '_constructor_sliced': 'Callable[..., Series]', '_AXIS_ORDERS': "list[Literal['index', 'columns']]", '_AXIS_TO_AXIS_NUMBER': 'dict[Axis, int]', '_info_axis_number': 'Literal[1]', '_info_axis_name': "Literal['columns']"}, '__doc__': '\n    Two-dimensional, size-mutable, potentially heterogeneous tabular data.\n\n    Data structure also contains labeled axes (rows and columns).\n    Arithmetic operations align on both row and column labels. Can be\n    thought of as a dict-like container for Series objects. The primary\n    pandas data structure.\n\n    Parameters\n    ----------\n    data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame\n        Dict can contain Series, arrays, constants, dataclass or list-like objects. If\n        data is a dict, column order follows insertion-order. If a dict contains Series\n   

In [143]:
d={}
d['K1']=[{"class":{"K1":10,"K2":20},"url":"https://www.abc.com"},
         {"class":{"K1":100,"K2":200},"url":"https://www.google.com"},
         {"class":{"K1":"D1","K2":"D2"}}]
d['K2']={'K1':{'K1':{'K1':[{'K1':'V1','K2':'V2'}]}}}
print(d)

{'K1': [{'class': {'K1': 10, 'K2': 20}, 'url': 'https://www.abc.com'}, {'class': {'K1': 100, 'K2': 200}, 'url': 'https://www.google.com'}, {'class': {'K1': 'D1', 'K2': 'D2'}}], 'K2': {'K1': {'K1': {'K1': [{'K1': 'V1', 'K2': 'V2'}]}}}}


In [145]:
import pprint
pprint.pprint(d)

{'K1': [{'class': {'K1': 10, 'K2': 20}, 'url': 'https://www.abc.com'},
        {'class': {'K1': 100, 'K2': 200}, 'url': 'https://www.google.com'},
        {'class': {'K1': 'D1', 'K2': 'D2'}}],
 'K2': {'K1': {'K1': {'K1': [{'K1': 'V1', 'K2': 'V2'}]}}}}


In [147]:
pprint.pprint(pandas.DataFrame.__dict__)

mappingproxy({'T': <property object at 0x00000257B5B336F0>,
              '_AXIS_LEN': 2,
              '_AXIS_ORDERS': ['index', 'columns'],
              '_AXIS_TO_AXIS_NUMBER': {0: 0,
                                       1: 1,
                                       'columns': 1,
                                       'index': 0,
                                       'rows': 0},
              '_HANDLED_TYPES': (<class 'pandas.core.series.Series'>,
                                 <class 'pandas.core.indexes.base.Index'>,
                                 <class 'pandas.core.arrays.base.ExtensionArray'>,
                                 <class 'numpy.ndarray'>),
              '__annotations__': {'_AXIS_ORDERS': "list[Literal['index', "
                                                  "'columns']]",
                                  '_AXIS_TO_AXIS_NUMBER': 'dict[Axis, int]',
                                  '_accessors': 'set[str]',
                                  '_constructor_s

Decorator - metaprogramming
            -----------------
               - add new features to an exisiting code
             python ------> product1 V1.0 ->customer End
                                ...                |
                            product2 V2.0 ->customer End .... 
                                ...
Web development
Home AboutUs  news ContactUs
               |->City1
               |->City2
.......................//Running 
Home AboutUs  news ContactUs
               |->City1
               |->City2
               |->City3 <== new feature
               |->City4 <== new feature

Home AboutUs  news ContactUs [Blog]
               |->City1          |__new feature
               |->City2
               |->City3
               |->City4


In [149]:
def f1(a):  # decorator function
    def f2(): # wrapper function
        a()
    return f2

def news1():
    print('City1 news page')

f1(news1)

<function __main__.f1.<locals>.f2()>

In [151]:
rv = f1(news1)
rv()

City1 news page


In [153]:
#rv = f1(news1)
#rv()
@f1
def news2():
    print('City2 news page')

news2()

City2 news page


In [155]:
news1()

City1 news page


In [157]:
@f1
def news3():
    print('City3 news page')

In [159]:
news3()

City3 news page


In [161]:
class cname:
    var = 120
    @classmethod
    def f1(cls):
        '''this is class method'''
        print(cls.var) # like cname.var  -> 120
        cls.var = 200 # like cname.var = 200


print(cname.var) # 120
cname.f1() # f1(cname)  Vs  obj.f1() ->f1(obj) ->def f1(self):
print('') # empty line
print(cname.var) # 200

120
120

200


In [163]:
import time
time.ctime()

'Mon Mar 17 14:52:16 2025'

In [165]:
class vendor:
    def __init__(self,vName,vGST):
        self.vName = vName
        self.vGST = vGST
        print(f'Vendor:{self.vName} registration is done!')
    def billing(self,pName,pCost=0.0,pQty=0):
        self.pName = pName
        self.pCost = pCost
        self.pQty = pQty
        self.tax = 0.18
        self.total = self.pQty * self.pCost
        self.gs = self.total + self.tax
        s1=f'VendorName:{self.vName}\tVendorGST:{self.vGST}\tProductName:{self.pName}\t'
        s2=f'Cost:{self.pCost}\tTax:{self.tax}\tTotal:{self.total}\tGS:{self.gs}\t'
        s3=f'Billing date/time:{time.ctime()}\n'
        with open('billing_info.log','a') as wobj:
            wobj.write(s1+s2+s3+'\n')

In [167]:
vobj1 = vendor('vABC','GST1234')

Vendor:vABC registration is done!


In [169]:
vobj1.billing('pX',1000,3)

In [171]:
vobj1.billing('pY',1250,2)

In [173]:
vobj2=vendor('vXYZ','GST9392')

Vendor:vXYZ registration is done!


In [175]:
vobj2.billing('pA',500,2)

In [177]:
vobj2.billing('pX',1523,2)

In [179]:
import os
os.getcwd()

'C:\\Users\\theeba'

In [181]:
import trading_app as tp
vobj1 = tp.vendor('vTom','GST31245')
vobj1.billing('HDD',5000,15)


Vendor:vTom registration is done!


In [ ]:
Inheritance
--------------
reusability

class pA:
    ....

class pB:
    ...
obj = pB()
obj.pAattribute ->AttributeError

class className(parentClassName): <== inheritance 
  ....
obj=className()
obj.<parentclassAttributes>


class customDataset(torch.utils.data.Dataset): <== inheritance
    ...

custom_dataset=customDataset()
--------------


In [183]:
class product:
    pid=101
    pname = 'pX'

class customer:
    cname='Mr.AB'

obj = customer()
obj.pid

AttributeError: 'customer' object has no attribute 'pid'

In [ ]:
>>> import trading_app
>>> import trading_app as tp
>>>
>>> vobj1 = tp.vendor('ABCDE','GST123131')
Vendor:ABCDE registration is done!
>>>
>>> vobj1.billing('pA',1000,3)
>>>
>>> import networkx as nx
>>> nx.Graph
<class 'networkx.classes.graph.Graph'>
>>>
>>> nx.Graph()
<networkx.classes.graph.Graph object at 0x000001A77D4CA7B0>
>>>

In [187]:
class product:
    pid=101
    pname = 'pX'

class customer(product): # inheritance   Vs   def function(argument):
    cname='Mr.AB'

obj = customer()
print(obj.pid,obj.pname,obj.cname)

101 pX Mr.AB


In [ ]:
file: test1.py                          file: test2.py
------------------                     --------------------
class product:                          import test1
    pid = 101                           class customer(test1.product):
    def fx(self):                              def fy(self):
        ...                                          ..
--------------------                  -----------------------

file: p1.py <== end user code
--------------
import test2
obj = test2.customer()
obj.fx()
obj.fy()
obj.pid
---------------

In [189]:
class product:
    pid=101
    pname = 'pX'

class customer(product): # inheritance   Vs   def function(argument):
    cname='Mr.AB'
    print('From customer class:',product.pid,product.pname)

obj = customer()
print(obj.pid,obj.pname,obj.cname)

From customer class: 101 pX
101 pX Mr.AB


In [ ]:
python < 2.6 
class cname(object):
    i = 10 ---------// ?

In [191]:
class box:
    bid = 101
box.__mro__

(__main__.box, object)

In [193]:
class product:
    pid=101
    pname = 'pX'

class customer(product): # inheritance   Vs   def function(argument):
    cname='Mr.AB'
    print('From customer class:',product.pid,product.pname)

customer.__mro__

From customer class: 101 pX


(__main__.customer, __main__.product, object)

In [199]:
class pA:
    pass
class pB:
    pass
class pC(pA,pB): # multipleinheritance
    pass

print(pA.__mro__)
print(pB.__mro__)
print(pC.__mro__)

(<class '__main__.pA'>, <class 'object'>)
(<class '__main__.pB'>, <class 'object'>)
(<class '__main__.pC'>, <class '__main__.pA'>, <class '__main__.pB'>, <class 'object'>)


In [201]:
class pA:
    pass
class pB(pA): # single inheritance
    pass
class pC(pA,pB): # multipleinheritance
    pass

print(pA.__mro__)
print(pB.__mro__)
print(pC.__mro__)

TypeError: Cannot create a consistent method resolution
order (MRO) for bases pA, pB

In [ ]:
# multilevel inheritance
class pA:
    pass
class pB(pA):
    pass
class pC(pB):
    pass
class pD(pC):
    pass
obj = pD()
obj.<pA attribute> #OK
obj.<pB attribute> #OK
obj.<pC attribute> #OK


In [203]:
class product:
    pid = 101

class customer(product):
    pid = 501
    pname = 'B1'

obj = customer()
obj.pid,obj.pid

(501, 501)

In [213]:
class product:
    pid = 101

class customer(product):
    mypid = product.pid
    pid = 605
    pname = 'B1'

obj = customer()
obj.pid,obj.mypid

(605, 101)

In [215]:
class pA:
    def display(self):
        print('display list of products')

class pB(pA):
    def display(self):
        print('list of files')

obj = pB()
obj.display()
obj.display()

list of files
list of files


In [219]:
class pA:
    def display(self):
        print('display list of products')

class pB(pA):
    def display(self):
        print('list of files')
        super().display() # invoke parent class display method

obj = pB()
obj.display()

list of files
display list of products


Functional style programming
--------------------------------
|->High order programming => functionA(anotherFunction) map(f1,...) filter(f1,...)

Functional programming
------------------------
lambda 
comprehension
generator 
map,filter,enumerate 

In [ ]:
lambda 
- python keyword
- unnamed function 
- logic is function call with arguments - return some Value
- this is not block style code
- supports arithmetic;relational;logical;membership;other expressions
- can invoke external functionCall
- lambda list of arguments:<basicOperation>

In [221]:
def f1(a1,a2):
    return a1+a2

f1(10,20)

30

In [225]:
f2=lambda a1,a2:a1+a2
f2(10,20)

30

In [227]:
f3=lambda a1:a1 >500
f3(560)

True

In [229]:
f3(140)

False

In [231]:
f4 = lambda a:a.upper()
f4('abc')

'ABC'

In [233]:
def F4(a):
    return a.upper()

F4('abc')

'ABC'

In [235]:
def fx(a):
    if(a >500 and a<600):
        a = 150
        return a+100
    elif(a >100 and a<200):
        return a+200
    else:
        return 600

In [237]:
f5 = lambda a1:fx(a1)
f5(560)

250

In [239]:
f5(167)

367

In [241]:
f5(350)

600

In [ ]:
comprehension - adding new data to an existing structure
-------------
  |->list comprehension - list append operation 
                            [value for iterable]
                                       ---(1)--
                              --(2)--
  |->dict comprehension - adding new data to an existing dict
                              {key:value for iterable}

In [243]:
# list comprehension

L = [] 
for var in range(1,11):
    r = var + 100
    L.append(r)
L

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

In [245]:
[var+100 for var in range(1,11)]

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

In [247]:
L = [] 
for var in range(1,11):
    if(var >5):
        r = var + 100
        L.append(r)
    else:
        r = var + 500
        L.append(r)
L

[501, 502, 503, 504, 505, 106, 107, 108, 109, 110]

In [251]:
# [True if condition else False for iterable ]

[var+100 if var>5 else var+500 for var in range(1,11)]


[501, 502, 503, 504, 505, 106, 107, 108, 109, 110]

In [253]:
L = [] 
for var in range(1,11):
    if(var >5):
        r = var + 100
        L.append(r)
L

[106, 107, 108, 109, 110]

In [255]:
[var+100 for var in range(1,11) if var >5]

[106, 107, 108, 109, 110]

In [257]:
{'K':[var+100 for var in range(1,11) if var >5]}

{'K': [106, 107, 108, 109, 110]}

In [261]:
{'K'+str(var):[var+100 for var in range(1,11) if var >5]}

{'K10': [106, 107, 108, 109, 110]}

In [273]:
# dict comprehension
{'K'+str(var): var+100 for var in range(1,6)}

{'K1': 101, 'K2': 102, 'K3': 103, 'K4': 104, 'K5': 105}

In [275]:
{'K'+str(var): var+100 for var in range(1,6) if var > 3}

{'K4': 104, 'K5': 105}

In [281]:
#Generator  - Function ->returns an address 
                       #------------------- yield value

def f1():
    return 10

print(type(f1),type(f1()))

def f2():
    yield 10

print(type(f2),type(f2()))

<class 'function'> <class 'int'>
<class 'function'> <class 'generator'>


>>> os.listdir("Rya-Project")
['L1', 'L2', 'p1.py', 'p2.py', 'p3.py', 'templates']
>>>
>>> os.walk("Rya-Project")
<generator object walk at 0x000001F5894B4320>
>>>
>>> gen_obj = os.walk("Rya-Project")
>>> for var in gen_obj:
...     print(var)
...
('Rya-Project', ['L1', 'L2', 'templates'], ['p1.py', 'p2.py', 'p3.py'])
('Rya-Project\\L1', ['S1', 'S2'], ['p2.log'])
('Rya-Project\\L1\\S1', [], ['p1.log'])
('Rya-Project\\L1\\S2', [], [])
('Rya-Project\\L2', [], [])
('Rya-Project\\templates', [], ['a.html', 'b.html', 'c.html', 'd.html', 'e.html'])
>>> bool([])
False
>>> gen_obj = os.walk("Rya-Project")
>>> list(gen_obj)
[('Rya-Project', ['L1', 'L2', 'templates'], ['p1.py', 'p2.py', 'p3.py']), ('Rya-Project\\L1', ['S1', 'S2'], ['p2.log']), ('Rya-Project\\L1\\S1', [], ['p1.log']), ('Rya-Project\\L1\\S2', [], []), ('Rya-Project\\L2', [], []), ('Rya-Project\\templates', [], ['a.html', 'b.html', 'c.html', 'd.html', 'e.html'])]
>>>

In [283]:
f2()

<generator object f2 at 0x00000257B5D63110>

In [285]:
def f2():
    yield 10
    yield 20
    yield 30
    yield 40
    yield 50+60
    yield "D1","D2"
    yield "D1",["F1","F2"],["F3","F4","F5"]

In [287]:
f2()

<generator object f2 at 0x00000257B81B5780>

In [ ]:
1. next(gen_obj) ->value... StopIteration
2. for var in gen_obj:
           ...
3. list(gen_obj) # typecast to list

In [289]:
gen_obj = f2()

In [291]:
print(next(gen_obj))
print(next(gen_obj))
print(next(gen_obj))
print(next(gen_obj))
print(next(gen_obj))
print(next(gen_obj))
print(next(gen_obj))
print(next(gen_obj))

10
20
30
40
110
('D1', 'D2')
('D1', ['F1', 'F2'], ['F3', 'F4', 'F5'])


StopIteration: 

In [293]:
gen_obj = f2()
for var in gen_obj:
    print(var)

10
20
30
40
110
('D1', 'D2')
('D1', ['F1', 'F2'], ['F3', 'F4', 'F5'])


In [295]:
gen_obj = f2()
list(gen_obj)

[10, 20, 30, 40, 110, ('D1', 'D2'), ('D1', ['F1', 'F2'], ['F3', 'F4', 'F5'])]

In [297]:
len(os.listdir('.'))

198

#for var in os.walk('.'):
#    print(var)

In [ ]:
map()      -> map(function,collection) -> Generator
                   ^^^^^     ^^^^^^
filter()   -> filter(function,collection) -> Generator
              -------//returns True value only

In [300]:
L = []
def f1(a):
    return a+100

for var in range(1,6):
    r = f1(var)
    L.append(r)

print(L)

[101, 102, 103, 104, 105]


In [302]:
map(lambda a:a+100,range(1,6))

In [304]:
list(map(lambda a:a+100,range(1,6)))

[101, 102, 103, 104, 105]

In [308]:
list(open('emp.csv')) 

['eid,ename,edept,eplace,ecost\n',
 '101,ram,sales,pune,1000\n',
 '102,leo,prod,bglore,2000\n',
 '103,anu,HR,hyd,3000\n',
 '104,paul,sales,bglore,3200\n',
 '423,zio,sales,pune,3420\n',
 '142,anu,prod,chennai,4300\n',
 '949,karthik,sales,bglore,3100\n',
 '848,tom,hr,chennai,3940\n',
 '931,vijay,prod,chennai,3411']

In [310]:
d={}
d['CSV']=list(open('emp.csv')) 
d

{'CSV': ['eid,ename,edept,eplace,ecost\n',
  '101,ram,sales,pune,1000\n',
  '102,leo,prod,bglore,2000\n',
  '103,anu,HR,hyd,3000\n',
  '104,paul,sales,bglore,3200\n',
  '423,zio,sales,pune,3420\n',
  '142,anu,prod,chennai,4300\n',
  '949,karthik,sales,bglore,3100\n',
  '848,tom,hr,chennai,3940\n',
  '931,vijay,prod,chennai,3411']}

In [312]:
list(map(lambda a:'sales' in a,open('emp.csv')))

[False, True, False, False, True, True, False, True, False, False]

In [314]:
list(filter(lambda a:'sales' in a,open('emp.csv')))

['101,ram,sales,pune,1000\n',
 '104,paul,sales,bglore,3200\n',
 '423,zio,sales,pune,3420\n',
 '949,karthik,sales,bglore,3100\n']

In [316]:
dept={} # create empty dict
dept['SALES']=list(filter(lambda a:'sales' in a,open('emp.csv'))) # add data to dict
dept['PROD']=list(filter(lambda a:'prod' in a,open('emp.csv'))) # add data to dict
dept['hr']=list(filter(lambda a:'hr' in a,open('emp.csv'))) # add data to dict

In [318]:
dept

{'SALES': ['101,ram,sales,pune,1000\n',
  '104,paul,sales,bglore,3200\n',
  '423,zio,sales,pune,3420\n',
  '949,karthik,sales,bglore,3100\n'],
 'PROD': ['102,leo,prod,bglore,2000\n',
  '142,anu,prod,chennai,4300\n',
  '931,vijay,prod,chennai,3411'],
 'hr': ['848,tom,hr,chennai,3940\n']}

In [320]:
list(map(lambda a:a+100,range(1,6)))

[101, 102, 103, 104, 105]

In [326]:
# filter - supports conditional based 
list(filter(lambda a:a+100,range(1,6)))

[1, 2, 3, 4, 5]

In [322]:
list(map(lambda a: a > 3,range(1,6)))

[False, False, False, True, True]

In [324]:
list(filter(lambda a:a>3,range(1,6)))

[4, 5]

In [330]:
#help(enumerate)
enumerate('python')

In [332]:
list(enumerate('python'))

[(0, 'p'), (1, 'y'), (2, 't'), (3, 'h'), (4, 'o'), (5, 'n')]

In [334]:
for var in enumerate('python'):
    print(var)

(0, 'p')
(1, 'y')
(2, 't')
(3, 'h')
(4, 'o')
(5, 'n')


In [336]:
for var in enumerate('python',5):
    print(var)

(5, 'p')
(6, 'y')
(7, 't')
(8, 'h')
(9, 'o')
(10, 'n')


In [338]:
for var in enumerate('python',15):
    print(var)

(15, 'p')
(16, 'y')
(17, 't')
(18, 'h')
(19, 'o')
(20, 'n')


In [340]:
for var in enumerate('python',500):
    print(var)

(500, 'p')
(501, 'y')
(502, 't')
(503, 'h')
(504, 'o')
(505, 'n')


In [ ]:
open emp.csv file - use enumerate
set the index count is 1
apply line filter - 5 to 8 
display 5th line to 8th line contents
--------------------------------------

In [342]:
enumerate(open('emp.csv'))

In [344]:
for var in enumerate(open('emp.csv')):
    print(var)

(0, 'eid,ename,edept,eplace,ecost\n')
(1, '101,ram,sales,pune,1000\n')
(2, '102,leo,prod,bglore,2000\n')
(3, '103,anu,HR,hyd,3000\n')
(4, '104,paul,sales,bglore,3200\n')
(5, '423,zio,sales,pune,3420\n')
(6, '142,anu,prod,chennai,4300\n')
(7, '949,karthik,sales,bglore,3100\n')
(8, '848,tom,hr,chennai,3940\n')
(9, '931,vijay,prod,chennai,3411')


In [348]:
for var in enumerate(open('emp.csv')):
    line,data = var # multiple initialization
    if(line >=5 and line <= 8):
        print(line,data.strip()) # remove \n

5 423,zio,sales,pune,3420
6 142,anu,prod,chennai,4300
7 949,karthik,sales,bglore,3100
8 848,tom,hr,chennai,3940


In [350]:
for var in enumerate(open('emp.csv'),1):
    line,data = var # multiple initialization
    if(line >=5 and line <= 8):
        print(line,data.strip()) # remove \n

5 104,paul,sales,bglore,3200
6 423,zio,sales,pune,3420
7 142,anu,prod,chennai,4300
8 949,karthik,sales,bglore,3100


In [354]:
[data.strip() for line,data in enumerate(open('emp.csv'),1) if line >= 5 and line <=8 ]

['104,paul,sales,bglore,3200',
 '423,zio,sales,pune,3420',
 '142,anu,prod,chennai,4300',
 '949,karthik,sales,bglore,3100']

In [356]:
d={}
d['K1']=[data.strip() for line,data in enumerate(open('emp.csv'),1) if line >= 5 and line <=8 ]
d

{'K1': ['104,paul,sales,bglore,3200',
  '423,zio,sales,pune,3420',
  '142,anu,prod,chennai,4300',
  '949,karthik,sales,bglore,3100']}

In [370]:
dept={} # create empty dict
dept['SALES']=list(filter(lambda a:'sales' in a,open('emp.csv'))) # add data to dict
dept['PROD']=list(filter(lambda a:'prod' in a,open('emp.csv'))) # add data to dict
dept['hr']=list(filter(lambda a:'hr' in a,open('emp.csv'))) # add data to dict
len(dept['SALES']),len(dept['PROD'])

(4, 3)

In [ ]:
numpy
--------
 ->mathematical operation
 |
 -> index ; slicing;reshape
 -> ufunctions


In [372]:
L1=[10,20,30,40,50]
L1+100

TypeError: can only concatenate list (not "int") to list

In [374]:
L1=[10,20,30]
L2=[15,25,35]
L1+L2

[10, 20, 30, 15, 25, 35]

In [376]:
L1 > 150

TypeError: '>' not supported between instances of 'list' and 'int'

In [378]:
L1.append("data")
L1

[10, 20, 30, 'data']

In [382]:
import array
#help(array.array)
arr = array.array('i')
arr.append(10)
arr.append(15)
arr.append(25)
arr

array('i', [10, 15, 25])

In [384]:
arr.append(35.0)

TypeError: 'float' object cannot be interpreted as an integer

In [386]:
arr

array('i', [10, 15, 25])

In [388]:
arr+100

TypeError: can only append array (not "int") to array

In [390]:
import numpy
numpy.array([10,20,30])

array([10, 20, 30])

In [392]:
a1 = numpy.array([10,20,30])
a1+100

array([110, 120, 130])

In [394]:
a1 >15

array([False,  True,  True])

In [396]:
a1[a1 >15] # boolean index

array([20, 30])

In [402]:
print(a1.dtype)
print(a1.ndim)
print(a1.shape)

int32
1
(3,)


In [406]:
a1 = numpy.array([10,20,30])
print(a1.dtype,a1.ndim,a1.shape)
print('') # empty line

a2 = numpy.array([[10,20,30]])
print(a2.dtype,a2.ndim,a2.shape)
print('') # empty line


a3 = numpy.array([[[10,20,30]]])
print(a3.dtype,a3.ndim,a3.shape)
print('') # empty line

int32 1 (3,)

int32 2 (1, 3)

int32 3 (1, 1, 3)



In [410]:
a1 = numpy.array([10,20,30])
print(a1.dtype,a1.ndim,a1.shape)
print(a1[0])
print('') # empty line

a2 = numpy.array([[10,20,30]])
print(a2.dtype,a2.ndim,a2.shape)
print(a2[0])
print(a2[0][0])
print(a2[0,0]) # same as a2[0][0]
print('') # empty line


a3 = numpy.array([[[10,20,30]]])
print(a3.dtype,a3.ndim,a3.shape)
print(a3[0])
print(a3[0][0])
print(a3[0][0][0])
print('') # empty line

int32 1 (3,)
10

int32 2 (1, 3)
[10 20 30]
10
10

int32 3 (1, 1, 3)
[[10 20 30]]
[10 20 30]
10



In [414]:
numpy.array([1,2,3]).dtype

dtype('int32')

In [416]:
numpy.array([1,2.0,3]).dtype

dtype('float64')

In [418]:
numpy.array([1,2.0,'data']).dtype

dtype('<U32')

In [422]:
numpy.array([True,False]).dtype

dtype('bool')

In [424]:
a1 = numpy.array([10,20,30]) # 1D - like list - index 

a2 = numpy.array([[10,20,30]]) # 2D Table ->Row X Cols

a3 = numpy.array([[[10,20,30]]]) # 3D Table - Slicing,Row X cols - cube width,height,depth

an = numpy.array([[[[[[[10,20]]]]]]])
an.ndim

7

In [439]:
# change the dimension - based on the avaiable of data

a1 = numpy.array([[10,20,30,40],[50,60,70,80]])
print(a1.ndim,a1.shape)
a1

2 (2, 4)


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [441]:
a1.reshape(4,2) # 4rows and 2 Cols

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [443]:
a1.reshape(1,8)

array([[10, 20, 30, 40, 50, 60, 70, 80]])

In [445]:
a1.reshape(8,1) # 8 Rows X 1 cols

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80]])

In [447]:
a1.reshape(3,2)

ValueError: cannot reshape array of size 8 into shape (3,2)

In [451]:
import numpy as np
print(np.sum(a1))
print(np.max(a1))
print(np.min(a1))

360
80
10


In [ ]:
     C1    C2    C3
R1    10   20    30
R2    40   50    60

In [453]:
a1 = np.array([[10,20,30],[40,50,60]])
np.sum(a1)

210

In [455]:
np.sum(a1,axis=0) # column

array([50, 70, 90])

In [457]:
np.sum(a1,axis=1) # row

array([ 60, 150])

np.sum
np.max
np.min
np.mean
np.median
np.unique
..

In [459]:
empCost = [100,200,300,400,500]

t=0
for var in empCost:
    t=t+var
print(t)

1500


In [461]:
np.sum(empCost) #<== numpy way

1500